Repository gluestack/gluestack-ui, pull requests merged in 2023-07, with the labels that each got.

#741 Fix/toast
  example/storybook/src/components/Feedback/Toast/index.stories.mdx
  example/storybook/src/ui-components/Toast/styled-components/Description.tsx
  example/storybook/src/ui-components/Toast/styled-components/Root.tsx
  example/storybook/src/ui-components/Toast/styled-components/Title.tsx
Labels: documentation, Design Changes

#730 Fix/badge
  example/storybook/junit.xml
  example/storybook/src/components/DataDisplay/Badge/Badge.tsx
  example/storybook/src/components/DataDisplay/Badge/index.stories.mdx
  example/storybook/src/components/Feedback/Alert/Variants.tsx
  example/storybook/src/components/Feedback/Alert/index.stories.mdx
  example/storybook/src/components/Feedback/Toast/Toast.tsx
  example/storybook/src/components/Forms/TextArea/index.stories.mdx
  example/storybook/src/ui-components/Alert/styled-components/Root.tsx
  example/storybook/src/ui-components/AlertDialog/styled-components/Backdrop.tsx
  example/storybook/src/ui-components/Badge/styled-components/Icon.tsx
  example/storybook/src/ui-components/Badge/styled-components/Root.tsx
  example/storybook/src/ui-components/Modal/styled-components/Backdrop.tsx
  example/storybook/src/ui-components/Popover/styled-components/Backdrop.tsx
  example/storybook/src/ui-components/Popover/styled-components/Content.tsx
Labels: documentation, Design Changes

#754 Feat/toast
  example/storybook/__tests__/__snapshots__/Box.test.js.snap
  example/storybook/__tests__/__snapshots__/Button.test.js.snap
  example/storybook/__tests__/__snapshots__/Checkbox.test.js.snap
  example/storybook/junit.xml
  example/storybook/src/components/DataDisplay/Badge/index.stories.mdx
  example/storybook/src/components/Feedback/Toast/Toast.tsx
  example/storybook/src/components/Feedback/Toast/index.stories.mdx
  example/storybook/src/components/MediaAndIcons/Icon/AllIcons.tsx
  example/storybook/src/components/MediaAndIcons/Icon/index.stories.mdx
  example/storybook/src/components/MediaAndIcons/Image/index.stories.mdx
  example/storybook/src/gluestack-ui.config.ts
  example/storybook/src/ui-components/Badge/styled-components/Root.tsx
  example/storybook/src/ui-components/Badge/styled-components/Text.tsx
  example/storybook/src/ui-components/Toast/styled-components/Root.tsx
Labels: documentation, Design Changes

#771 fix: changes hex code in secondary,error,sucess
  example/storybook/__tests__/__snapshots__/Button.test.js.snap
  example/storybook/__tests__/__snapshots__/Checkbox.test.js.snap
  example/storybook/junit.xml
  example/storybook/src/gluestack-ui.config.ts
Labels: Design Changes

#765 Fix/menu
  example/storybook/__tests__/__snapshots__/Button.test.js.snap
  example/storybook/src/components/Disclosure/Actionsheet/index.stories.mdx
  example/storybook/src/components/Layout/Box/index.stories.mdx
  example/storybook/src/components/Overlay/Menu/Menu.tsx
  example/storybook/src/components/Overlay/Menu/index.stories.mdx
  example/storybook/src/components/Overlay/Modal/index.stories.mdx
  example/storybook/src/components/Typography/Heading/index.stories.mdx
  example/storybook/src/components/Typography/Text/index.stories.mdx
  example/storybook/src/ui-components/Button/styled-components/Root.tsx
  example/storybook/src/ui-components/Menu/styled-components/Backdrop.tsx
  example/storybook/src/ui-components/Menu/styled-components/Item.tsx
  example/storybook/src/ui-components/Menu/styled-components/Item.web.tsx
  example/storybook/src/ui-components/Menu/styled-components/ItemLabel.tsx
Labels: documentation, Design Changes

#775 Fix/overlay components
  example/storybook/src/components/Forms/Switch/index.stories.mdx
  example/storybook/src/components/Overlay/AlertDialog/index.stories.mdx
  example/storybook/src/components/Overlay/Menu/Menu.tsx
  example/storybook/src/components/Overlay/Modal/index.stories.mdx
  example/storybook/src/components/Overlay/Popover/index.stories.mdx
  example/storybook/src/ui-components/AlertDialog/styled-components/Backdrop.tsx
  example/storybook/src/ui-components/AlertDialog/styled-components/Body.tsx
  example/storybook/src/ui-components/AlertDialog/styled-components/Content.tsx
  example/storybook/src/ui-components/AlertDialog/styled-components/Footer.tsx
  example/storybook/src/ui-components/AlertDialog/styled-components/Header.tsx
  example/storybook/src/ui-components/Modal/styled-components/Backdrop.tsx
  example/storybook/src/ui-components/Modal/styled-components/Body.tsx
  example/storybook/src/ui-components/Modal/styled-components/Content.tsx
  example/storybook/src/ui-components/Modal/styled-components/Footer.tsx
  example/storybook/src/ui-components/Modal/styled-components/Header.tsx
  example/storybook/src/ui-components/Popover/styled-components/Backdrop.tsx
  example/storybook/src/ui-components/Popover/styled-components/Content.tsx
  example/storybook/src/ui-components/Popover/styled-components/Header.tsx
  example/storybook/src/ui-components/Toast/styled-components/Root.tsx
  example/storybook/src/ui-components/Toast/styled-components/Title.tsx
Labels: documentation, Design Changes

#702 Feat/slider
  example/expo-project/gluestack-ui.config.ts
  example/storybook/babel.config.js
  example/storybook/package.json
  example/storybook/src/components/Forms/Slider/Slider.stories.tsx
  example/storybook/src/components/Forms/Slider/Slider.tsx
  example/storybook/src/components/Forms/Slider/index.stories.mdx
  example/storybook/src/gluestack-ui.config.ts
  example/storybook/src/ui-components/Slider/styled-components/FilledTrack.tsx
  example/storybook/src/ui-components/Slider/styled-components/Root.tsx
  example/storybook/src/ui-components/Slider/styled-components/Thumb.tsx
  example/storybook/src/ui-components/Slider/styled-components/Track.tsx
  packages/slider/src/Slider.tsx
  packages/slider/src/SliderFilledTrack.tsx
  packages/slider/src/SliderThumb.tsx
  packages/slider/src/SliderTrack.tsx
  yarn.lock
Labels: documentation, Design Changes

#670 Fix/select and actionsheet styled
  example/next-project/package.json
  example/storybook/.ondevice/storybook.requires.js
  example/storybook/__tests__/__snapshots__/Box.test.js.snap
  example/storybook/__tests__/__snapshots__/Button.test.js.snap
  example/storybook/__tests__/__snapshots__/Checkbox.test.js.snap
  example/storybook/junit.xml
  example/storybook/src/components/Disclosure/Actionsheet/Actionsheet.tsx
  example/storybook/src/components/Forms/Select/Select.tsx
  example/storybook/src/components/Forms/Select/index.stories.mdx
  example/storybook/src/components/Overlay/Menu/Menu.tsx
  example/storybook/src/gluestack-ui.config.ts
  example/storybook/src/ui-components/Actionsheet/styled-components/Backdrop.tsx
  example/storybook/src/ui-components/Actionsheet/styled-components/Content.tsx
  example/storybook/src/ui-components/Actionsheet/styled-components/DragIndicator.tsx
  example/storybook/src/ui-components/Actionsheet/styled-components/Icon.tsx
  example/storybook/src/ui-components/Actionsheet/styled-components/IndicatorWrapper.tsx
  example/storybook/src/ui-components/Actionsheet/styled-components/Item.tsx
  example/storybook/src/ui-components/Actionsheet/styled-components/ItemText.tsx
  example/storybook/src/ui-components/Actionsheet/styled-components/SectionHeaderText.tsx
  example/storybook/src/ui-components/AlertDialog/styled-components/Backdrop.tsx
  example/storybook/src/ui-components/Icons/index.tsx
  example/storybook/src/ui-components/Input/styled-components/Root.tsx
  example/storybook/src/ui-components/Menu/styled-components/Backdrop.tsx
  example/storybook/src/ui-components/Menu/styled-components/Item.tsx
  example/storybook/src/ui-components/Menu/styled-components/Item.web.tsx
  example/storybook/src/ui-components/Menu/styled-components/ItemLabel.tsx
  example/storybook/src/ui-components/Menu/styled-components/Root.tsx
  example/storybook/src/ui-components/Modal/styled-components/Backdrop.tsx
  example/storybook/src/ui-components/Popover/styled-components/Backdrop.tsx
  example/storybook/src/ui-components/Select/styled-components-actionsheet/Backdrop.tsx
  example/storybook/src/ui-components/Select/styled-components-actionsheet/Content.tsx
  example/storybook/src/ui-components/Select/styled-components-actionsheet/DragIndicator.tsx
  example/storybook/src/ui-components/Select/styled-components-actionsheet/Icon.tsx
  example/storybook/src/ui-components/Select/styled-components-actionsheet/IndicatorWrapper.tsx
  example/storybook/src/ui-components/Select/styled-components-actionsheet/Item.tsx
  example/storybook/src/ui-components/Select/styled-components-actionsheet/ItemText.tsx
  example/storybook/src/ui-components/Select/styled-components-actionsheet/SectionHeaderText.tsx
  example/storybook/src/ui-components/Select/styled-components/Input.tsx
  example/storybook/src/ui-components/Select/styled-components/Root.tsx
  example/storybook/src/ui-components/Select/styled-components/Trigger.tsx
  packages/actionsheet/src/ActionsheetContent.tsx
  packages/select/src/Select.tsx
  packages/select/src/SelectInput.tsx
  packages/select/src/SelectPortal.tsx
  yarn.lock
Labels: documentation, Design Changes, Require package release

#787 Feat/tooltip
  example/storybook/src/components/Overlay/Tooltip/Tooltip.tsx
  example/storybook/src/components/Overlay/Tooltip/index.stories.mdx
  example/storybook/src/ui-components/Tooltip/index.tsx
  example/storybook/src/ui-components/Tooltip/styled-components/Text.tsx
  example/storybook/src/ui-components/Tooltip/styled-components/index.tsx
  packages/tooltip/src/TooltipText.tsx
  packages/tooltip/src/index.tsx
  packages/tooltip/src/types.ts
Labels: documentation, Design Changes, Require package release

#773 fix: toast
  example/storybook/src/components/Feedback/Toast/Toast.stories.tsx
  example/storybook/src/components/Feedback/Toast/Toast.tsx
  example/storybook/src/components/Feedback/Toast/index.stories.mdx
  example/storybook/src/ui-components/Toast/styled-components/Root.tsx
  packages/toast/src/Toast.tsx
  packages/toast/src/ToastTitle.tsx
  packages/toast/src/types.ts
Labels: documentation, TypeScript, Design Changes, Require package release
