Repository gluestack/gluestack-ui, pull requests merged in 2023-06, with the labels that each got.

#660 Fix/exampless issue
  example/storybook/package.json
  example/storybook/src/components/DataDisplay/Badge/index.stories.mdx
  example/storybook/src/components/DataDisplay/Divider/index.stories.mdx
  example/storybook/src/components/Feedback/Alert/Variants.tsx
  example/storybook/src/components/Feedback/Alert/index.stories.mdx
  example/storybook/src/components/Forms/Button/index.stories.mdx
  example/storybook/src/components/Forms/Input/index.stories.mdx
  example/storybook/src/components/Forms/Switch/Switch.tsx
  example/storybook/src/components/Layout/Center/index.stories.mdx
  example/storybook/src/components/Layout/HStack/index.stories.mdx
  example/storybook/src/components/Layout/VStack/index.stories.mdx
  example/storybook/src/components/MediaAndIcons/Image/index.stories.mdx
  example/storybook/src/components/Others/Fab/index.stories.mdx
  example/storybook/src/components/Overlay/AlertDialog/index.stories.mdx
  example/storybook/src/components/Overlay/Popover/index.stories.mdx
  example/storybook/src/components/Overlay/Tooltip/index.stories.mdx
  example/storybook/src/components/Typography/Heading/index.stories.mdx
  example/storybook/src/components/Typography/Text/index.stories.mdx
  example/storybook/src/ui-components/Alert/styled-components/Root.tsx
  example/storybook/src/ui-components/Alert/styled-components/Text.tsx
  example/storybook/src/ui-components/Slider/styled-components/Thumb.tsx
  packages/switch/src/types.ts
  yarn.lock
Labels: Design Changes, Require package release

#672 fix: colors tokens
  example/storybook/src/gluestack-ui.config.ts
Labels: Design Changes

#683 fix: lg size issues
  example/storybook/src/ui-components/Badge/styled-components/Root.tsx
Labels: Design Changes

#688 Feat / box shadow
  example/expo-project/package.json
  example/next-project/package.json
  example/storybook/__tests__/__snapshots__/Box.test.js.snap
  example/storybook/__tests__/__snapshots__/Button.test.js.snap
  example/storybook/__tests__/__snapshots__/Checkbox.test.js.snap
  example/storybook/package.json
  example/storybook/src/components/Overlay/Popover/Popover.tsx
  example/storybook/src/components/Overlay/Popover/index.stories.mdx
  example/storybook/src/gluestack-ui.config.ts
  example/storybook/src/ui-components/AlertDialog/styled-components/Content.tsx
  example/storybook/src/ui-components/Fab/styled-components/Root.tsx
  example/storybook/src/ui-components/Menu/styled-components/Root.tsx
  example/storybook/src/ui-components/Modal/styled-components/Content.tsx
  example/storybook/src/ui-components/Popover/styled-components/Backdrop.tsx
  example/storybook/src/ui-components/Popover/styled-components/Content.tsx
  example/storybook/src/ui-components/Popover/styled-components/Footer.tsx
  example/storybook/src/ui-components/Popover/styled-components/Header.tsx
  example/storybook/src/ui-components/Popover/styled-components/Root.tsx
  example/storybook/src/ui-components/Toast/styled-components/Root.tsx
  example/storybook/src/ui-components/Tooltip/styled-components/Content.tsx
  packages/popover/src/PopoverContent.tsx
  yarn.lock
Labels: Design Changes

#696 Feat/image
  example/storybook/.ondevice/storybook.requires.js
  example/storybook/src/components/MediaAndIcons/Image/Image.stories.tsx
  example/storybook/src/components/MediaAndIcons/Image/Image.tsx
  example/storybook/src/components/MediaAndIcons/Image/index.stories.mdx
  example/storybook/src/ui-components/Image/styled-components/Root.tsx
Labels: documentation

#681 Feat/icon
  example/storybook/src/components/MediaAndIcons/Icon/AllIcons.tsx
  example/storybook/src/components/MediaAndIcons/Icon/index.stories.mdx
  example/storybook/src/ui-components/Icons/index.tsx
Labels: documentation, Design Changes

#671 fix: docs and styling
  example/storybook/src/components/Forms/Switch/index.stories.mdx
  example/storybook/src/ui-components/Switch/styled-components/Root.tsx
Labels: documentation, Design Changes

#669 fix: placeholder style
  example/storybook/src/components/Forms/TextArea/index.stories.mdx
  example/storybook/src/ui-components/Textarea/styled-components/Input.tsx
  example/storybook/src/ui-components/Textarea/styled-components/Root.tsx
Labels: documentation, Design Changes

#673 fix: docs
  example/storybook/src/components/Overlay/AlertDialog/index.stories.mdx
Labels: documentation

#705 Fix/popover
  example/storybook/src/components/Overlay/Popover/Popover.tsx
  example/storybook/src/components/Overlay/Popover/index.stories.mdx
  example/storybook/src/ui-components/Popover/styled-components/Backdrop.tsx
  example/storybook/src/ui-components/Popover/styled-components/CloseButton.tsx
  example/storybook/src/ui-components/Popover/styled-components/Content.tsx
  example/storybook/src/ui-components/Popover/styled-components/Footer.tsx
Labels: documentation, Design Changes, Require package release

#709 Fix/example content
  example/storybook/src/components/DataDisplay/Badge/index.stories.mdx
  example/storybook/src/components/DataDisplay/Divider/index.stories.mdx
  example/storybook/src/components/Disclosure/Actionsheet/index.stories.mdx
  example/storybook/src/components/Feedback/Alert/index.stories.mdx
  example/storybook/src/components/Feedback/Progress/index.stories.mdx
  example/storybook/src/components/Feedback/Spinner/index.stories.mdx
  example/storybook/src/components/Feedback/Toast/index.stories.mdx
  example/storybook/src/components/Forms/Button/index.stories.mdx
  example/storybook/src/components/Forms/Checkbox/index.stories.mdx
  example/storybook/src/components/Forms/FormControl/index.stories.mdx
  example/storybook/src/components/Forms/Input/index.stories.mdx
  example/storybook/src/components/Forms/Link/index.stories.mdx
  example/storybook/src/components/Forms/Pressable/index.stories.mdx
  example/storybook/src/components/Forms/Radio/index.stories.mdx
  example/storybook/src/components/Forms/Select/index.stories.mdx
  example/storybook/src/components/Forms/Slider/index.stories.mdx
  example/storybook/src/components/Forms/Switch/index.stories.mdx
  example/storybook/src/components/Forms/Tabs/index.stories.mdx
  example/storybook/src/components/Forms/TextArea/index.stories.mdx
  example/storybook/src/components/Layout/Box/index.stories.mdx
  example/storybook/src/components/Layout/Center/index.stories.mdx
  example/storybook/src/components/Layout/HStack/index.stories.mdx
  example/storybook/src/components/Layout/VStack/index.stories.mdx
  example/storybook/src/components/MediaAndIcons/Avatar/index.stories.mdx
  example/storybook/src/components/MediaAndIcons/Icon/index.stories.mdx
  example/storybook/src/components/MediaAndIcons/Image/index.stories.mdx
  example/storybook/src/components/Others/Fab/index.stories.mdx
  example/storybook/src/components/Overlay/AlertDialog/index.stories.mdx
  example/storybook/src/components/Overlay/Menu/index.stories.mdx
  example/storybook/src/components/Overlay/Modal/index.stories.mdx
  example/storybook/src/components/Overlay/Popover/index.stories.mdx
  example/storybook/src/components/Overlay/Tooltip/index.stories.mdx
  example/storybook/src/components/Provider/Provider/index.stories.mdx
  example/storybook/src/components/Typography/Heading/index.stories.mdx
  example/storybook/src/components/Typography/Text/index.stories.mdx
Labels: documentation
